Controllers/InoutController.cs
using System;
using System.Collections.Generic;

using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Fixture02.Models;

namespace Fixture02.Controllers
{
    public class InoutController : Controller
    {
        private fixtureEntities db = new fixtureEntities();

        // GET: Jigitems
        public ActionResult Index(String code, String name, String location , String model, String partNo)
        {
            
            var jigitem = from m in this.db.Jigitem select m;
            if (!String.IsNullOrEmpty(code))
            {
                jigitem = jigitem.Where(h => h.Code.Contains(code));
            }
            if (!String.IsNullOrEmpty(location))
            {
                jigitem = jigitem.Where(h => h.Location.Contains(location));
            }

            OutJigList outJigList = new OutJigList();
            outJigList.OutModelList = new List<OutJig>();
            foreach(var jigmodel in jigitem)
            {
                Jig jig = db.Jig.Find(jigmodel.Code);
                if(!String.IsNullOrEmpty(name) && jig.Name != name)
                {
                    continue;
                }
                if (!String.IsNullOrEmpty(model) && jig.Model != model)
                {
                    continue;
                }
                if (!String.IsNullOrEmpty(partNo) && jig.PartNo != partNo)
                {
                    continue;
                }
                outJigList.OutModelList.Add(
                    new OutJig { Code = jigmodel.Code, Name = jig.Name, Model = jig.Model, PartNo = jig.PartNo, State = jigmodel.State ,Location = jigmodel.Location,ItemID = jigmodel.ItemID}
                );
            }
          
            return View(outJigList);
        }
        public ActionResult InIndex(String code, String name, String location, String model, String partNo)
        {
            var jigitem = from m in this.db.Jigitem select m;
            jigitem = jigitem.Where(p => p.State == "出库" || p.State == "领用");
            if (!String.IsNullOrEmpty(code))
            {
                jigitem = jigitem.Where(h => h.Code.Contains(code));
            }
            if (!String.IsNullOrEmpty(location))
            {
                jigitem = jigitem.Where(h => h.Location.Contains(location));
            }

            OutJigList outJigList = new OutJigList();
            outJigList.OutModelList = new List<OutJig>();
            foreach (var jigmodel in jigitem)
            {
                Jig jig = db.Jig.Find(jigmodel.Code);
                if (!String.IsNullOrEmpty(name) && jig.Name != name)
                {
                    continue;
                }
                if (!String.IsNullOrEmpty(model) && jig.Model != model)
                {
                    continue;
                }
                if (!String.IsNullOrEmpty(partNo) && jig.PartNo != partNo)
                {
                    continue;
                }
                outJigList.OutModelList.Add(
                    new OutJig { Code = jigmodel.Code, Name = jig.Name, Model = jig.Model, PartNo = jig.PartNo, State = jigmodel.State, Location = jigmodel.Location, ItemID = jigmodel.ItemID }
                );
            }

            return View(outJigList);
        }
        // GET: Jigitems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Inout inout = db.Inout.Find(id);
            if (inout == null)
            {
                return HttpNotFound();
            }
            return View(inout);
        }

        // GET: Jigitems/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Jigitems/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IinOutID,ItemID,ViaUserName,State,LineID,LineName,Code,Name,Location,Model,PartNo,FamilyID,FamilyName,AddDate,AddUserID,AddUserName,ReviewDate,ReviewUserID,ReviewUserName,SecondReviewDate")] Inout inout)
        {
            if (ModelState.IsValid)
            {
                db.Inout.Add(inout);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(inout);
        }

        // GET: Jigitems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Inout inout = db.Inout.Find(id);
            if (inout == null)
            {
                return HttpNotFound();
            }
            return View(inout);
        }

        // POST: Jigitems/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IinOutID,ItemID,ViaUserName,State,LineID,LineName,Code,Name,Location,Model,PartNo,FamilyID,FamilyName,AddDate,AddUserID,AddUserName,ReviewDate,ReviewUserID,ReviewUserName,SecondReviewDate")] Inout inout)
        {
            if (ModelState.IsValid)
            {
                db.Entry(inout).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(inout);
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Inout inout = db.Inout.Find(id);
            if (inout == null)
            {
                return HttpNotFound();
            }
            return View(inout);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id)
        {
            Inout inout = db.Inout.Find(id);
            db.Inout.Remove(inout);
            db.SaveChanges();
            return RedirectToAction("SearchInoutMessage");
        }

        // GET: Jigitems/Delete/5
        public ActionResult OutStorage(OutJig item)
        {
            return View(item);
        }

        // POST: Jigitems/Delete/5
        [HttpPost]
        public ActionResult OutStorage(Inout item)
        {
            item.AddDate = System.DateTime.Now;
            if(db.Inout.Select(e => e.IinOutID).Any())
            {
                int maxLinOutID = db.Inout.Select(e => e.IinOutID).Max();
                item.IinOutID = maxLinOutID + 1;
            }
            Jigitem jig = (from c in db.Jigitem
                             where c.ItemID == item.ItemID
                             select c).Single();
            jig.State = item.State;
            this.db.Inout.Add(
                item);
            this.db.SaveChanges();

            return RedirectToAction("Index");
        }

       
        public ActionResult InStorage(OutJig item)
        {

            return View(item);
        }

        // POST: Jigitems/Delete/5
        [HttpPost]
        public ActionResult InStorageToSql(Inout item)
        {
            item.AddDate = System.DateTime.Now;
            if ( db.Inout.Select(e => e.IinOutID).Any())
            {
                int maxLinOutID = db.Inout.Select(e => e.IinOutID).Max();
                item.IinOutID = maxLinOutID + 1;
            }
            Jigitem jig = (from c in db.Jigitem
                           where c.ItemID == item.ItemID
                           select c).Single();
            jig.State = "库存";
            this.db.Inout.Add(
                item);
            this.db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult SearchInoutMessage(String code, String name, String location, String model, String partNo)
        {
            var inoutitem = from m in this.db.Inout select m;
            if (!String.IsNullOrEmpty(code))
            {
                inoutitem = inoutitem.Where(h => h.Code.Contains(code));
            }
            if (!String.IsNullOrEmpty(location))
            {
                inoutitem = inoutitem.Where(h => h.Location.Contains(location));
            }
            if (!String.IsNullOrEmpty(model))
            {
                inoutitem = inoutitem.Where(h => h.Model.Contains(model));
            }
            if (!String.IsNullOrEmpty(name))
            {
                inoutitem = inoutitem.Where(h => h.Name.Contains(name));
            }
            if (!String.IsNullOrEmpty(partNo))
            {
                inoutitem = inoutitem.Where(h => h.PartNo.Contains(partNo));
            }

            return View(inoutitem);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }


    public class OutJig
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public string PartNo { get; set; }
        public string State { get; set; }
        public string Location{ get; set; }
        public int ItemID { get; set; }
    }

    public class OutJigList
    {
        public List<OutJig> OutModelList{get; set;}
    }
}

Controllers/repairsController.cs
using System;
using System.Collections.Generic;

using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Fixture02.Models;

namespace Fixture02.Controllers
{
    public class RepairsController : Controller
    {
        private fixtureEntities db = new fixtureEntities();

        // GET: repairs
        public ActionResult Index()
        {
            return View(db.repair.ToList());
        }

        // GET: repairs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            repair repair = db.repair.Find(id);
            if (repair == null)
            {
                return HttpNotFound();
            }
            return View(repair);
        }

        // GET: repairs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: repairs/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RepairID,CheckID,ItemID,Code,Name,FamilyID,FamilyName,Model,PartNo,Problem,Pic,AddDate,AddUserID,AddUserName,RepairDate,RepairUserName,RepairState")] repair repair)
        {
            if (ModelState.IsValid)
            {
                repair.AddDate = DateTime.Now;
                repair.RepairState = "新增";
                db.repair.Add(repair);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(repair);
        }

        // GET: repairs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            repair repair = db.repair.Find(id);
            if (repair == null)
            {
                return HttpNotFound();
            }
            return View(repair);
        }

        // POST: repairs/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RepairID,CheckID,ItemID,Code,Name,FamilyID,FamilyName,Model,PartNo,Problem,Pic,AddDate,AddUserID,AddUserName,RepairDate,RepairUserName,RepairState")] repair repair)
        {
            if (ModelState.IsValid)
            {
                db.Entry(repair).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(repair);
        }

        // GET: repairs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            repair repair = db.repair.Find(id);
            if (repair == null)
            {
                return HttpNotFound();
            }
            return View(repair);
        }

        // POST: repairs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            repair repair = db.repair.Find(id);
            db.repair.Remove(repair);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //the action below is written by fangyu

        public ActionResult RepairHandling()            /*前往报修处理界面*/
        {
            return View(db.repair.ToList());
        }

        public ActionResult RepairSuccess(int? id)          /*修复成功*/
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            repair repair = db.repair.Find(id);
            if (repair == null)
            {
                return HttpNotFound();
            }
            repair.RepairState = "修复";
            repair.RepairDate = DateTime.Now;
            //repair.RepairUserName = Session.User.username;
            repair.RepairUserName = "session.user.username";
            db.SaveChanges();
            changeJigitemState(repair.ItemID, "维修");
            return RedirectToAction("Index");
        }

        public ActionResult RepairFail(int? id)         /*修复失败*/
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            repair repair = db.repair.Find(id);
            if (repair == null)
            {
                return HttpNotFound();
            }
            repair.RepairState = "未修复";
            repair.RepairDate = DateTime.Now;
            //repair.RepairUserName = Session.User.username;
            repair.RepairUserName = "session.user.username";
            db.SaveChanges();
            changeJigitemState(repair.ItemID, "报废");
            return RedirectToAction("Index");
        }

        public ActionResult changeJigitemState(int? itemid,string statename)
        {
            if (itemid == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            repair repair = db.repair.Find(itemid);
            if (repair == null)
            {
                return HttpNotFound();
            }
            var otherController = DependencyResolver.Current.GetService<JigitemsController>();
            var action = otherController.changeItemState(itemid,statename);
            return action;
        }
    }
}

Views/Shared/FixtureMaster.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>智能工夹具管理系统</title>

    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
    <div class="container">
        <div class="row clearfix">
            <div class="col-md-12 column">
                <h3 class="text-center">
                    工夹具智能管理系统
                </h3>
            </div>
        </div>


        <div class="row clearfix">
            <div class="col-md-2 column">
                <div class="panel-group" id="panel-756431">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                          
                            @Html.ActionLink("首页", "Index", "Home")
                        </div>
                    </div>


                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <a class="panel-title collapsed" data-toggle="collapse" data-parent="#panel-756431" href="#panel-element-528672">采购入库</a>
                        </div>

                        <div id="panel-element-528672" class="panel-collapse collapse">
                            <div class="panel-body">
                                @Html.ActionLink("采购入库登记", "Index", "Jigitems")
                            </div>

                            <div class="panel-body">
                                @Html.ActionLink("采购入库初审", "FirstReview", "Jigitems")
                            </div>

                            <div class="panel-body">
                                @Html.ActionLink("采购入库终审", "SecondReview", "Jigitems")
                            </div>

                            <div class="panel-body">
                                @Html.ActionLink("采购入库查询", "FixtureItemFind", "Jigitems")
                            </div>

                        </div>
                    </div>


                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <a class="panel-title collapsed" data-toggle="collapse" data-parent="#panel-756431" href="#panel-element-21442">进/出库</a>
                        </div>

                        <div id="panel-element-21442" class="panel-collapse collapse">
                            <div class="panel-body">
                                @Html.ActionLink("入库管理", "InIndex", "Inout")
                            </div>

                            <div class="panel-body">
                                @Html.ActionLink("出库管理", "Index", "Inout")
                            </div>

                            <div class="panel-body">
                                @Html.ActionLink("信息查询", "SearchInoutMessage", "Inout")
                            </div>
                        </div>
                    </div>


                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <a class="panel-title collapsed" data-toggle="collapse" data-parent="#panel-756431" href="#panel-element-21443">工夹具报修</a>
                        </div>


                        <div id="panel-element-21443" class="panel-collapse collapse">
                            <div class="panel-body">
                                @Html.ActionLink("报修提交", "create", "Repairs")
                            </div>

                            <div class="panel-body">
                                @Html.ActionLink("报修处理", "RepairHandling", "Repairs")
                            </div>

                            <div class="panel-body">
                                @Html.ActionLink("报修查询", "index", "Repairs")
                            </div>
                        </div>
                    </div>


                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <a class="panel-title collapsed" data-toggle="collapse" data-parent="#panel-756431" href="#panel-element-21444">工夹具报废</a>
                        </div>


                        <div id="panel-element-21444" class="panel-collapse collapse">
                            <div class="panel-body">
                                <a href="#">报废提交</a>
                            </div>

                            <div class="panel-body">
                                <a href="#">报废初审</a>
                            </div>

                            <div class="panel-body">
                                <a href="#">报废终审</a>
                            </div>

                            <div class="panel-body">
                                <a href="#">报废查询</a>
                            </div>
                        </div>
                    </div>



                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <a class="panel-title collapsed" data-toggle="collapse" data-parent="#panel-756431" href="#panel-element-21445">系统管理</a>
                        </div>


                        <div id="panel-element-21445" class="panel-collapse collapse">
                            <div class="panel-body">
                                @Html.ActionLink("用户管理", "EmployeeIndex", "Employees")
                            </div>

                            <div class="panel-body">
                                @Html.ActionLink("部门管理", "Index", "Workcells")
                            </div>

                            <div class="panel-body">
                                <a href="#">权限管理</a>
                            </div>
                        </div>
                    </div>


                </div>
            </div>
            <div class="col-md-10 column">
                @RenderBody()
            </div>
        </div>

    </div>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 应用程序</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("应用程序名称", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("关于", "About", "Home")</li>
                    <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">



        @RenderBody()




        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 应用程序</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>