Controllers/InoutController.cs
using System;
using System.Collections.Generic;

using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Fixture02.Models;

namespace Fixture02.Controllers
{
    public class InoutController : Controller
    {
        private fixtureEntities db = new fixtureEntities();

        // GET: Jigitems
        public ActionResult Index(String code, String name, String location , String model, String partNo)
        {
            
            var jigitem = from m in this.db.Jigitem select m;
            if (!String.IsNullOrEmpty(code))
            {
                jigitem = jigitem.Where(h => h.Code.Contains(code));
            }
            if (!String.IsNullOrEmpty(location))
            {
                jigitem = jigitem.Where(h => h.Location.Contains(location));
            }

            OutJigList outJigList = new OutJigList();
            outJigList.OutModelList = new List<OutJig>();
            foreach(var jigmodel in jigitem)
            {
                Jig jig = db.Jig.Find(jigmodel.Code);
                if(!String.IsNullOrEmpty(name) && jig.Name != name)
                {
                    continue;
                }
                if (!String.IsNullOrEmpty(model) && jig.Model != model)
                {
                    continue;
                }
                if (!String.IsNullOrEmpty(partNo) && jig.PartNo != partNo)
                {
                    continue;
                }
                outJigList.OutModelList.Add(
                    new OutJig { Code = jigmodel.Code, Name = jig.Name, Model = jig.Model, PartNo = jig.PartNo, State = jigmodel.State ,Location = jigmodel.Location,ItemID = jigmodel.ItemID}
                );
            }
          
            return View(outJigList);
        }
        public ActionResult InIndex(String code, String name, String location, String model, String partNo)
        {
            var jigitem = from m in this.db.Jigitem select m;
            jigitem = jigitem.Where(p => p.State == "出库" || p.State == "领用");
            if (!String.IsNullOrEmpty(code))
            {
                jigitem = jigitem.Where(h => h.Code.Contains(code));
            }
            if (!String.IsNullOrEmpty(location))
            {
                jigitem = jigitem.Where(h => h.Location.Contains(location));
            }

            OutJigList outJigList = new OutJigList();
            outJigList.OutModelList = new List<OutJig>();
            foreach (var jigmodel in jigitem)
            {
                Jig jig = db.Jig.Find(jigmodel.Code);
                if (!String.IsNullOrEmpty(name) && jig.Name != name)
                {
                    continue;
                }
                if (!String.IsNullOrEmpty(model) && jig.Model != model)
                {
                    continue;
                }
                if (!String.IsNullOrEmpty(partNo) && jig.PartNo != partNo)
                {
                    continue;
                }
                outJigList.OutModelList.Add(
                    new OutJig { Code = jigmodel.Code, Name = jig.Name, Model = jig.Model, PartNo = jig.PartNo, State = jigmodel.State, Location = jigmodel.Location, ItemID = jigmodel.ItemID }
                );
            }

            return View(outJigList);
        }
        // GET: Jigitems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Inout inout = db.Inout.Find(id);
            if (inout == null)
            {
                return HttpNotFound();
            }
            return View(inout);
        }

        // GET: Jigitems/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Jigitems/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IinOutID,ItemID,ViaUserName,State,LineID,LineName,Code,Name,Location,Model,PartNo,FamilyID,FamilyName,AddDate,AddUserID,AddUserName,ReviewDate,ReviewUserID,ReviewUserName,SecondReviewDate")] Inout inout)
        {
            if (ModelState.IsValid)
            {
                db.Inout.Add(inout);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(inout);
        }

        // GET: Jigitems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Inout inout = db.Inout.Find(id);
            if (inout == null)
            {
                return HttpNotFound();
            }
            return View(inout);
        }

        // POST: Jigitems/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IinOutID,ItemID,ViaUserName,State,LineID,LineName,Code,Name,Location,Model,PartNo,FamilyID,FamilyName,AddDate,AddUserID,AddUserName,ReviewDate,ReviewUserID,ReviewUserName,SecondReviewDate")] Inout inout)
        {
            if (ModelState.IsValid)
            {
                db.Entry(inout).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(inout);
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Inout inout = db.Inout.Find(id);
            if (inout == null)
            {
                return HttpNotFound();
            }
            return View(inout);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id)
        {
            Inout inout = db.Inout.Find(id);
            db.Inout.Remove(inout);
            db.SaveChanges();
            return RedirectToAction("SearchInoutMessage");
        }

        // GET: Jigitems/Delete/5
        public ActionResult OutStorage(OutJig item)
        {
            return View(item);
        }

        // POST: Jigitems/Delete/5
        [HttpPost]
        public ActionResult OutStorage(Inout item)
        {
            item.AddDate = System.DateTime.Now;
            if(db.Inout.Select(e => e.IinOutID).Any())
            {
                int maxLinOutID = db.Inout.Select(e => e.IinOutID).Max();
                item.IinOutID = maxLinOutID + 1;
            }
            Jigitem jig = (from c in db.Jigitem
                             where c.ItemID == item.ItemID
                             select c).Single();
            jig.State = item.State;
            this.db.Inout.Add(
                item);
            this.db.SaveChanges();

            return RedirectToAction("Index");
        }

       
        public ActionResult InStorage(OutJig item)
        {

            return View(item);
        }

        // POST: Jigitems/Delete/5
        [HttpPost]
        public ActionResult InStorageToSql(Inout item)
        {
            item.AddDate = System.DateTime.Now;
            if ( db.Inout.Select(e => e.IinOutID).Any())
            {
                int maxLinOutID = db.Inout.Select(e => e.IinOutID).Max();
                item.IinOutID = maxLinOutID + 1;
            }
            Jigitem jig = (from c in db.Jigitem
                           where c.ItemID == item.ItemID
                           select c).Single();
            jig.State = "库存";
            this.db.Inout.Add(
                item);
            this.db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult SearchInoutMessage(String code, String name, String location, String model, String partNo)
        {
            var inoutitem = from m in this.db.Inout select m;
            if (!String.IsNullOrEmpty(code))
            {
                inoutitem = inoutitem.Where(h => h.Code.Contains(code));
            }
            if (!String.IsNullOrEmpty(location))
            {
                inoutitem = inoutitem.Where(h => h.Location.Contains(location));
            }
            if (!String.IsNullOrEmpty(model))
            {
                inoutitem = inoutitem.Where(h => h.Model.Contains(model));
            }
            if (!String.IsNullOrEmpty(name))
            {
                inoutitem = inoutitem.Where(h => h.Name.Contains(name));
            }
            if (!String.IsNullOrEmpty(partNo))
            {
                inoutitem = inoutitem.Where(h => h.PartNo.Contains(partNo));
            }

            return View(inoutitem);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }


    public class OutJig
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public string PartNo { get; set; }
        public string State { get; set; }
        public string Location{ get; set; }
        public int ItemID { get; set; }
    }

    public class OutJigList
    {
        public List<OutJig> OutModelList{get; set;}
    }
}

Controllers/JigitemsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Runtime.Remoting.Messaging;
using System.Web;
using System.Web.Mvc;
using Fixture02.Models;

namespace Fixture02.Controllers
{
    public class JigitemsController : Controller
    {
        private fixtureEntities db = new fixtureEntities();

        // GET: Jigitems
        public ActionResult Index()
        {
            var state = from m in this.db.Jigitem select m;
            state = state.Where(h => h.State.Equals("新增") || h.State.Equals("退回"));

            return View(state);
        }

        // GET: Jigitems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Jigitem jigitem = db.Jigitem.Find(id);
            if (jigitem == null)
            {
                return HttpNotFound();
            }
            return View(jigitem);
        }

        // GET: Jigitems/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ItemID,Code,SeqID,BillNo,RegDate,Location,State,Pic,AddDate,AddUserID,AddUserName")] Jigitem jigitem)
        {
            if (ModelState.IsValid)
            {
                jigitem.UsedCount = 0;
                jigitem.State = "新增";
                jigitem.AddDate = DateTime.Now;
                jigitem.AddUserID = "010";
                jigitem.AddUserName = "李观星";

                db.Jigitem.Add(jigitem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(jigitem);
        }

        // GET: Jigitems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Jigitem jigitem = db.Jigitem.Find(id);
            if (jigitem == null)
            {
                return HttpNotFound();
            }
            return View(jigitem);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ItemID,Code,SeqID,BillNo,RegDate,UsedCount,Location,State,Pic,AddDate,AddUserID,AddUserName,FirstReviewDate,FirstReviewUserID,FirstReviewUserName,SecondReviewDate,SecondReviewUserID,SecondReviewUserName,WaitTime,BackNote")] Jigitem jigitem)
        {
            if (ModelState.IsValid)
            {
                jigitem.State = "新增";
                db.Entry(jigitem).State = EntityState.Modified;
                
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(jigitem);
        }


        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Jigitem jigitem = db.Jigitem.Find(id);
            if (jigitem == null)
            {
                return HttpNotFound();
            }
            return View(jigitem);
        }

        // POST: Jigitems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Jigitem jigitem = db.Jigitem.Find(id);
            db.Jigitem.Remove(jigitem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        //初审管理

        public ActionResult FirstReview()
        {
            var state = from m in this.db.Jigitem select m;
            state = state.Where(h => h.State.Equals("新增"));

            return View(state);
        }

        [HttpPost]
        public ActionResult FirstReview(int id,string state)
        {
            Jigitem jigitem = db.Jigitem.Find(id);
            string backnote = Request["backNote"];

            if (state=="同意")
            {
                jigitem.State = "初审";
            }
            else
            {
                jigitem.State = "退回";
                jigitem.BackNote = backnote;
            }
            
            jigitem.FirstReviewDate = DateTime.Now;
            jigitem.FirstReviewUserID = "011";
            jigitem.FirstReviewUserName = "llggxx";
            

            db.SaveChanges();
            return RedirectToAction("FirstReview");
        }


        //终审管理
        public ActionResult SecondReview()
        {
            var state = from m in this.db.Jigitem select m;
            state = state.Where(h => h.State.Equals("初审"));

            return View(state);
        }

        [HttpPost]
        public ActionResult SecondReview(int id, string state)
        {
            Jigitem jigitem = db.Jigitem.Find(id);
            string backnote = Request["backNote"];

            if (state == "同意")
            {
                jigitem.State = "终审";
            }
            else
            {
                jigitem.State = "退回";
                jigitem.BackNote = backnote;
            }

            jigitem.SecondReviewDate = DateTime.Now;
            jigitem.SecondReviewUserID = "022";
            jigitem.SecondReviewUserName = "llggxx2";

            db.SaveChanges();
            return RedirectToAction("SecondReview");
        }

        //采购入库查询
        public ActionResult FixtureItemFind(String code, String location, String state)
        {
            var name = from m in this.db.Jigitem select m;
            if (!String.IsNullOrEmpty(code))
            {
                name = name.Where(h => h.Code.Contains(code));
            }
            if (!String.IsNullOrEmpty(location))
            {
                name = name.Where(h => h.Location.Contains(location));
            }
            if (!String.IsNullOrEmpty(state))
            {
                name = name.Where(h => h.State.Contains(state));
            }
            return View(name);
        }

        public ActionResult EditItem(int id,string state)
        {
            Jigitem jigitem = db.Jigitem.Find(id);

            if(state == "退回")
            {
                jigitem.State = "新增";
            }
            
            db.SaveChanges();
            return RedirectToAction("Edit");
        }


        //change the state of item
        public ActionResult changeItemState(int? itemid, string statename)
        {
            if (itemid == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Jigitem jigitem = db.Jigitem.Find(itemid);
            if (jigitem == null)
            {
                return HttpNotFound();
            }
            jigitem.State = statename;
            db.SaveChanges();
            return null;
        }
    }
}

Views/Inout/InIndex.cshtml
@model Fixture02.Controllers.OutJigList

@{
    Layout = "~/Views/Shared/FixtureMaster.cshtml";
}

    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Index</title>
    </head>
    <body>
        <div class="container-fluid">
            <div class="row-fluid">

                <p>

                    @using (Html.BeginForm("Index", "Inout", FormMethod.Get))
                    {
                        <table class="table">
                            <tr>
                                <th>夹具编号:@Html.TextBox("code")</th>
                                <th>夹具名称:@Html.TextBox("name")</th>
                                <th>夹具库位:@Html.TextBox("location")</th>
                                <th>夹具模组:@Html.TextBox("model")</th>
                                <th>夹具料号:@Html.TextBox("partNO")</th>
                                <th> <button class="btn" type="submit">查询</button></th>
                            </tr>
                        </table>

                    }
                </p>

            </div>
        </div>
        <table class="table">
            <tr>
                <th>
                    Code
                </th>
                <th>
                    Name
                </th>
                <th>
                    Location
                </th>
                <th>
                    Model
                </th>
                <th>
                    PartNo
                </th>
                <th>
                    state
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.OutModelList)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Code)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Location)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Model)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PartNo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.State)
                    </td>
                    <td>
                        @Html.ActionLink("编辑", "Edit","Jigitems", new { id = item.ItemID }) |
                        @Html.ActionLink("详情", "Details","Jigitems", new { id = item.ItemID }) |
                        @Html.ActionLink("入库", "InStorage", item)
                    </td>
                </tr>
            }

        </table>
    </body>
    </html>

Views/Inout/InStorage.cshtml
@model Fixture02.Controllers.OutJig

@{
    Layout = "~/Views/Shared/FixtureMaster.cshtml";
}
<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <div class="tabbable" id="tabs-383386">
                <ul class="nav nav-tabs">
                    <li class="active">
                        <a href="#panel-156784" data-toggle="tab">入库</a>
                    </li>
                    <li>
                        <a href="#panel-466615" data-toggle="tab">入缓冲区</a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="panel-156784">
                        <div class="container">
                            <div class="row clearfix">
                                <div class="col-md-12 column">
                                    @using (Html.BeginForm("InStorageToSql", "Inout"))
                                    {
                                        DateTime DT = System.DateTime.Now;
                                        string dt = DT.ToString();               //获取当前时间
                                        <label>夹具编码</label>@Html.TextBox("Code", "", new { @class = "form-control" })
                                        <label>夹具名称</label>@Html.TextBox("Name", "", new { @class = "form-control" })
                                        <label>夹具位置</label>@Html.TextBox("Location", "", new { @class = "form-control" })
                                        <label>经手人</label>@Html.TextBox("ViaUserName")<label>创建人</label>@Html.TextBox("AddUserName")<label>审核人</label>@Html.TextBox("ReviewUserName")
                                        <br><label>夹具生产线</label>@Html.TextBox("LineName", "", new { @class = "form-control" })
                                        @Html.Hidden("ItemID", Model.ItemID)
                                        <input type="hidden" name="State" id="State" value="进库" />
                                        @Html.Hidden("AddUserId", 123)
                                        @Html.Hidden("Model", Model.Model)
                                        @Html.Hidden("PartNo", Model.PartNo)
                                        <button type="submit" class="btn btn-default">操作并记录</button>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane" id="panel-466615">
                        <div class="container">
                            <div class="row clearfix">
                                <div class="col-md-12 column">
                                    @using (Html.BeginForm("InStorageToSql", "Inout"))
                                    {
                                        DateTime DT = System.DateTime.Now;
                                        string dt = DT.ToString();               //获取当前时间
                                        <label>夹具编码</label>@Html.TextBox("Code", "", new { @class = "form-control" })
                                        <label>夹具名称</label>@Html.TextBox("Name", "", new { @class = "form-control" })
                                        <label>夹具位置</label>@Html.TextBox("Location", "", new { @class = "form-control" })
                                        <label>经手人</label>@Html.TextBox("ViaUserName")<label>创建人</label>@Html.TextBox("AddUserName")<label>审核人</label>@Html.TextBox("ReviewUserName")
                                        <br><label>领用地点</label>@Html.TextBox("LineName", "", new { @class = "form-control" })
                                        @Html.Hidden("ItemID", Model.ItemID)
                                        <input type="hidden" name="State" id="State" value="缓冲" />
                                        @Html.Hidden("AddUserId", 123)
                                        @Html.Hidden("Model", Model.Model)
                                        @Html.Hidden("PartNo", Model.PartNo)
                                        <button type="submit" class="btn btn-default">操作并记录</button>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Inout/Index.cshtml
@model Fixture02.Controllers.OutJigList

@{
     Layout = "~/Views/Shared/FixtureMaster.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div class="container-fluid">
        <div class="row-fluid">

            <p>

                @using (Html.BeginForm("Index", "Inout", FormMethod.Get))
                {
                   <table class="table"> 
                       <tr>
                           <th>夹具编号:@Html.TextBox("code")</th>
                           <th>夹具名称:@Html.TextBox("name")</th>
                           <th>夹具库位:@Html.TextBox("location")</th>
                           <th>夹具模组:@Html.TextBox("model")</th>
                           <th>夹具料号:@Html.TextBox("partNO")</th>
                           <th> <button class="btn" type="submit">查询</button></th>
                       </tr>
                   </table>

            }
                </p>

            </div>
        </div>
        <table class="table">
            <tr>
                <th>
                    Code
                </th>
                <th>
                    Name
                </th>
                <th>
                    Location
                </th>
                <th>
                    Model
                </th>
                <th>
                    PartNo
                </th>
                <th>
                    state
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model.OutModelList)
            {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PartNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.ActionLink("编辑", "Edit","Jigitems", new { id = item.ItemID}) |
                @Html.ActionLink("详情", "Details","Jigitems", new { id = item.ItemID }) |
                @Html.ActionLink("出库", "OutStorage", item)
            </td>
        </tr>
            }

        </table>
    </body>
</html>

Views/Inout/OutStorage.cshtml
@model Fixture02.Controllers.OutJig

@{
         Layout = "~/Views/Shared/FixtureMaster.cshtml";
}
    <div class="container">
        <div class="row clearfix">
            <div class="col-md-12 column">
                <div class="tabbable" id="tabs-383386">
                    <ul class="nav nav-tabs">
                        <li class="active">
                            <a href="#panel-156784" data-toggle="tab">出库</a>
                        </li>
                        <li>
                            <a href="#panel-466615" data-toggle="tab">临时领用</a>
                        </li>
                    </ul>
                    <div class="tab-content">
                        <div class="tab-pane active" id="panel-156784">
                            <div class="container">
                                <div class="row clearfix"> 
                                    <div class="col-md-12 column">
                                        @using (Html.BeginForm("OutStorage", "Inout"))
                                        {
                                            <label>夹具编码</label>@Html.TextBox("Code", "", new { @class = "form-control" })
                                            <label>夹具名称</label>@Html.TextBox("Name", "", new { @class = "form-control" })
                                            <label>夹具位置</label>@Html.TextBox("Location", "", new { @class = "form-control" })
                                            <label>经手人</label>@Html.TextBox("ViaUserName")<label>创建人</label>@Html.TextBox("AddUserName")<label>审核人</label>@Html.TextBox("ReviewUserName")
                                            <br><label>夹具生产线</label>@Html.TextBox("LineName", "", new { @class = "form-control" })
                                            <input type="hidden" name="State" id="State" value="出库"/>
                                            @Html.Hidden("ItemID", Model.ItemID)
                                                                 
                                            @Html.Hidden("AddUserId", 123)
                                            @Html.Hidden("Model", Model.Model)
                                            @Html.Hidden("PartNo", Model.PartNo)

                                            <button type="submit" class="btn btn-default">操作并记录</button>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="tab-pane" id="panel-466615">
                            <div class="container">
                                <div class="row clearfix">
                                    <div class="col-md-12 column">
                                        @using (Html.BeginForm("OutStorage", "Inout"))
                                        {
                                            DateTime DT = System.DateTime.Now;
                                            string dt = DT.ToString();               //获取当前时间
                                            <label>夹具编码</label>@Html.TextBox("Code", "", new { @class = "form-control" })
                                            <label>夹具名称</label>@Html.TextBox("Name", "", new { @class = "form-control" })
                                            <label>夹具位置</label>@Html.TextBox("Location", "", new { @class = "form-control" })
                                            <label>经手人</label>@Html.TextBox("ViaUserName")<label>创建人</label>@Html.TextBox("AddUserName")<label>审核人</label>@Html.TextBox("ReviewUserName")
                                            <br><label>领用地点</label>@Html.TextBox("LineName", "", new { @class = "form-control" })
                                            @Html.Hidden("ItemID", Model.ItemID)
                                            <input type="hidden" name="State" id="State" value="领用" /> 
                                            @Html.Hidden("AddUserId", 123)
                                            @Html.Hidden("Model", Model.Model)
                                            @Html.Hidden("PartNo", Model.PartNo)
             
                                            <button type="submit" class="btn btn-default">操作并记录</button>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>